name: Deploy to Railway

on:
  push:
    branches: [production]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package


  deploy:
     runs-on: ubuntu-latest
     steps:
      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
      - name: Deployment
        run: railway up
        env:
          RAILWAY_TOKEN: 611645f2-8ffd-4f1c-b0fc-0693c49d6ff0
